### ISSUE TITLE
How best to generate thumbnails?

### ISSUE THREAD

**Issue by anandthakker** [hotosm/oam-uploader-api#11]
From what I can tell, generating thumbnails is gonna be a bit hacky no matter what we do.  When we're adding imagery manually to the s3 buckets, we've just been using `gdal_translate` to resize the image and output as JPG, but the problem is that `node-gdal` only exposes bindings to the underlying gdal library, [not utilities like `gdal_translate`](https://github.com/naturalatlas/node-gdal/issues/67#issuecomment-58454986).

I guess we should either:

1. Use docker to get `gdal` (or `imagemagick`).  (There are heroku buildpacks for these too, but that makes it less useful for someone who wants to deploy elsewhere.)
2. Find some node lib that doesn't have an external dep and can handle TIFFs

**Comment by anandthakker** [comment]
cc: @scisco @lossyrob

**Comment by scisco** [comment]
Heroku's buildpack is just an installation mechanism. Instead of `apt-get install gdal` a buildpack is used. I think we can still easily reuse the code on any machine that has gdal or imagemagick installed if we go with option (1).

Option (2) certainly looks better if we can find such library. :+1:

**Comment by anandthakker** [comment]
It's looking like (2) isn't really an option;  I'm considering using https://github.com/lovell/sharp

**Comment by anandthakker** [comment]
Follow up in #14
