### ISSUE TITLE
Increase upload file max size

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-uploader-api#43]
As already discussed, the upload process can't handle files bigger than ~10GB.

Let's increase temp storage to allow uploading of bigger files (up to 50GB?)

**Comment by nbumbarger** [comment]
As mentioned [here](https://github.com/hotosm/oam-uploader-api/issues/58#issuecomment-270014198), due to processing overhead we should make sure the storage is at least double the size of any expected input file (depending on how gdal handles its own processing cache, it may be safer to assume ~3x).

**Comment by nbumbarger** [comment]
Actually, I'm not yet sure whether the processing overhead was a factor or not, but I just realized that there was hard 5GB limit on uploads, which I [increased](https://github.com/hotosm/oam-uploader-api/pull/53/commits/a7001bcb9a6c21fb918e3358ad63282a45fb9f4e) to 50GB.

**Comment by smit1678** [comment]
I've redeployed the Upload API on a bigger instance. The main issue was that there was only ~10GB of free. We're now backed with 1TB storage and so we shouldn't run into space issues. Going close this out as this should be good for now.
